#Makefile for find-MCIS (Maximal Common Induced Subgraph)

LIBRARIES=Protein.c MPG.c ProteinParser.c Logger.c

GCC_OPTIONS=-g

compile:
	gcc -o ../Target/find-MCIS find-MCIS.c ${LIBRARIES} -lm ${GCC_OPTIONS}

#EOF
